### ISSUE TITLE
Deletes more than it should

### ISSUE THREAD

**Issue by GhavynH** [JaxonTekk/HubPets#5]
**Describe the bug**
Deletes items in second slot to replace. deleted lots of pets and entities on the map.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Minecraft Version (please complete the following information):**
 - Version: [ 1.16.3]

**Java Version (please complete the following information)**
 - Java Version: [eg. Java 14]

**Additional context**

**Comment by jasoon-chen** [comment]
I'm not sure that I fully understand the problem that you are mentioning. Possibly reword it?

**Comment by GhavynH** [comment]
> I'm not sure that I fully understand the problem that you are mentioning. Possibly reword it?

yeah my bad, i was occupied at the time. when i used the plugin it deleted and replaced the second item in each persons hotbar. then it also deleted a large amount of pets people already had around the map.

**Comment by jasoon-chen** [comment]
Did you set `pet-tool` to true in the config? If so, then it's supposed to replace the 2nd slot in each persons hotbar (unless you changed it). I'm not sure about how it deleted the pets, but I can take a closer look at it.
